# -*- coding: utf-8 -*-
"""Data Analysis Project in Python(COVID-19).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LlNLxVFHcaF4HnacAapJqLXElnv37FeB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.subplots import make_subplots
from datetime import datetime

covid_df = pd.read_csv("covid_19_india.csv")

covid_df.head()

covid_df.info()

covid_df.describe()

vaccine_df = pd.read_csv("covid_vaccine_statewise.csv")

vaccine_df.head()

covid_df.drop(['Sno', 'ConfirmedIndianNational', 'ConfirmedForeignNational'], inplace=True, axis=1)

covid_df.head()

covid_df['Date'] = pd.to_datetime(covid_df['Date'], format = '%Y-%m-%d')

# active cases

covid_df['ActiveCases'] = covid_df['Confirmed'] - (covid_df['Cured'] + covid_df['Deaths'])
covid_df.tail()

statewise = pd.pivot_table(covid_df, values = ['Confirmed', 'Deaths', 'Cured'], index = 'State/UnionTerritory', aggfunc = max)

statewise['Recovery Rate'] = statewise['Cured']*100/statewise['Confirmed']

statewise['Mortality Rate'] = statewise['Deaths']*100/statewise['Confirmed']

statewise = statewise.sort_values(by = 'Confirmed', ascending = False)

statewise.style.background_gradient(cmap="cubehelix")

top_10_states = covid_df.groupby(by = 'State/UnionTerritory').max()[['ActiveCases', 'Date']].sort_values(by=["ActiveCases"], ascending = False).reset_index()

fig = plt.figure(figsize=(16,9))

plt.title("Top 10 state with most active cases in India", size = 25)

ax = sns.barplot(data = top_10_states.iloc[:10], y = "ActiveCases", x = 'State/UnionTerritory', linewidth = 2, edgecolor = "#ffcccb")

top_10_states = covid_df.groupby(by = 'State/UnionTerritory').max()[['ActiveCases', 'Date']].sort_values(by=["ActiveCases"],
                                                                                                         ascending = False).reset_index()
fig = plt.figure(figsize=(16,9))
plt.title("Top 10 state with most active cases in India", size = 25)
ax = sns.barplot(data = top_10_states.iloc[:10], y = "ActiveCases", x = 'State/UnionTerritory', linewidth = 2, edgecolor = "#ffcccb")
plt.xlabel("States")
plt.ylabel("Top Active Cases")
plt.show()



"""Data Analysis Project in Python(COVID-19).ipynb

You can visit infomenter.com for full article with explaination
"""

